name: Generate Java Pages

on:
  push:
    branches: [ gh-pages ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: read folder versions into data versions csv
        run: bash .github/generate-pages.sh
        env:
          VERSIONS_FILE: _data/versions.csv
          VERSION_PAGES_LOCATION: pages/versions
          TEMPLATES_LOCATION: .github/templates
      - name: commit changes
        uses: EndBug/add-and-commit@v8.0.1



